name: Install and DU Core install

env:
  DB_DATABASE: test_db
  DB_USER: root
  DB_PASSWORD: root
  
on:
  pull_request:
    branches: [ master ]

jobs:
  install_drush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-suggest

      - name: Add Drush to PATH
        run: |
          echo "PATH=$PATH:./vendor/bin" >> $GITHUB_PATH
          echo "PATH=$PATH:./vendor/bin"
          echo "PATH"

      - name: Start MySQL
        run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Test DU Core Install
        run: |
          drush si ducore -y --db-url=mysql://$DB_USER:$DB_PASSWORD@localhost:port3306/$DB_DATABASE